import { useNavigate } from "react-router-dom";
import { useAuth } from "@/context/AuthContext";
import { ArrowRight, Zap, Search, BarChart3, CreditCard, CheckCircle, Star } from "lucide-react";
import { SplineScene } from "@/components/ui/splite";
import { Spotlight } from "@/components/ui/spotlight";
import { Card } from "@/components/ui/card";

// REMINDER: DO NOT HARDCODE THE URL, OR ADD ANY FALLBACKS OR REDIRECT URLS, THIS BREAKS THE AUTH

const integrations = [
  "Apify", "Gumloop", "Jasper.ai", "lemlist", "HeyGen",
  "OpusClip", "Northbeam", "Attio", "Tidio", "Fireflies", "Texts.com", "Stripe"
];

const features = [
  { icon: Search, title: "AI Discovery Engine", desc: "Live scraping + AI scoring identifies the perfect micro and mid-tier creators for your brand in minutes, not days." },
  { icon: Zap, title: "Automated Outreach", desc: "Personalised email and DM sequences generated by AI, sent automatically with smart follow-up triggers." },
  { icon: BarChart3, title: "ROI Analytics", desc: "Real-time attribution dashboard showing reach, conversions, and ROAS per creator and campaign." },
  { icon: CreditCard, title: "Escrow Payments", desc: "Funds held securely until content is approved. Automatic release with full audit trail for both parties." },
];

const pricing = [
  { name: "Starter", price: 299, desc: "Perfect for small brands", features: ["Up to 3 active campaigns", "20 creator searches/mo", "Basic analytics", "Email outreach"], highlight: false },
  { name: "Growth", price: 599, desc: "Most popular", features: ["Up to 10 active campaigns", "Unlimited creator searches", "Full analytics + ROAS", "AI outreach + briefs", "Stripe escrow payments"], highlight: true },
  { name: "Scale", price: 1299, desc: "For agencies & power users", features: ["Unlimited campaigns", "White-label reports", "Priority AI processing", "Dedicated account manager", "API access"], highlight: false },
];

const steps = [
  { num: "01", title: "Enter your brief", desc: "Tell us your product, target audience, budget, and platforms. Takes 2 minutes." },
  { num: "02", title: "Get your shortlist", desc: "AI scores and ranks the top 20 creators matched to your exact campaign criteria." },
  { num: "03", title: "Launch your campaign", desc: "Approve outreach, sign briefs, track content, and pay — all in one place." },
];

export default function LandingPage() {
  const navigate = useNavigate();
  const { user } = useAuth();

  const handleCTA = () => {
    if (user) {
      navigate("/dashboard");
      return;
    }
    // REMINDER: DO NOT HARDCODE THE URL, OR ADD ANY FALLBACKS OR REDIRECT URLS, THIS BREAKS THE AUTH
    const redirectUrl = window.location.origin + "/dashboard";
    window.location.href = `https://auth.emergentagent.com/?redirect=${encodeURIComponent(redirectUrl)}`;
  };

  return (
    <div className="min-h-screen bg-[#0A0F2E] text-white overflow-x-hidden">

      {/* ── Sticky Navbar ── */}
      <header className="sticky top-0 z-50 bg-[#0A0F2E]/80 backdrop-blur-xl border-b border-white/5">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-[#00D4C8] flex items-center justify-center">
              <Zap className="w-4 h-4 text-[#0A0F2E]" strokeWidth={2.5} />
            </div>
            <span className="font-heading font-bold text-white text-lg">Influencer Connect</span>
          </div>
          <nav className="hidden md:flex items-center gap-6 text-sm text-white/60">
            <a href="#how-it-works" className="hover:text-white transition-colors">How it works</a>
            <a href="#features" className="hover:text-white transition-colors">Features</a>
            <a href="#pricing" className="hover:text-white transition-colors">Pricing</a>
          </nav>
          <button
            onClick={handleCTA}
            data-testid="nav-cta-btn"
            className="btn-primary px-5 py-2 rounded-lg text-sm"
          >
            {user ? "Go to Dashboard" : "Get Started"}
          </button>
        </div>
      </header>

      {/* ── HERO — Spline 3D Split Layout ── */}
      <section className="px-4 sm:px-6 pt-8 pb-6">
        <div className="max-w-7xl mx-auto">
          <Card
            className="w-full min-h-[580px] bg-black/[0.96] relative overflow-hidden border-white/[0.08] hero-card-glow"
            data-testid="hero-spline-card"
          >
            {/* Spotlight effect — teal tinted for brand consistency */}
            <Spotlight
              className="-top-40 left-0 md:left-60 md:-top-20"
              fill="#00D4C8"
            />

            <div className="flex flex-col md:flex-row h-full min-h-[580px]">

              {/* ── Left: Text Content ── */}
              <div className="flex-1 p-8 md:p-12 lg:p-16 relative z-10 flex flex-col justify-center">

                {/* Badge */}
                <div className="inline-flex items-center gap-2 bg-[#00D4C8]/10 border border-[#00D4C8]/25 rounded-full px-4 py-1.5 text-[#00D4C8] text-xs font-semibold uppercase tracking-widest mb-7 w-fit animate-fade-in">
                  <Zap className="w-3 h-3" /> AI-Powered Influencer Marketing
                </div>

                {/* Headline */}
                <h1 className="font-heading font-black text-4xl md:text-5xl lg:text-6xl leading-[1.05] tracking-tighter mb-5 animate-fade-up">
                  <span className="bg-clip-text text-transparent bg-gradient-to-b from-neutral-50 to-neutral-400">
                    Find, Brief &amp; Pay<br />
                    Influencers in<br />
                    Minutes.
                  </span>
                  <span className="block text-[#00D4C8]">Not Weeks.</span>
                </h1>

                {/* Subheadline */}
                <p className="text-neutral-400 text-base md:text-lg max-w-md mb-8 leading-relaxed animate-fade-up stagger-2">
                  The AI agent that replaces manual creator research, scattered spreadsheets,
                  and slow outreach — with a single intelligent system.
                </p>

                {/* CTAs */}
                <div className="flex flex-col sm:flex-row gap-3 mb-8 animate-fade-up stagger-3">
                  <button
                    onClick={handleCTA}
                    data-testid="hero-cta-btn"
                    className="btn-primary px-7 py-3.5 rounded-xl text-base flex items-center gap-2 justify-center"
                  >
                    Start Your Campaign <ArrowRight className="w-5 h-5" />
                  </button>
                  <a
                    href="#how-it-works"
                    className="btn-secondary px-7 py-3.5 rounded-xl text-base text-center"
                  >
                    See How It Works
                  </a>
                </div>

                {/* Social proof chips */}
                <div className="flex flex-wrap gap-3 text-xs text-white/40 animate-fade-up stagger-4">
                  <span className="flex items-center gap-1.5">
                    <CheckCircle className="w-3.5 h-3.5 text-[#00D4C8]" /> No credit card required
                  </span>
                  <span className="flex items-center gap-1.5">
                    <CheckCircle className="w-3.5 h-3.5 text-[#00D4C8]" /> Live in 5 minutes
                  </span>
                  <span className="flex items-center gap-1.5">
                    <CheckCircle className="w-3.5 h-3.5 text-[#00D4C8]" /> 500+ creators indexed
                  </span>
                </div>
              </div>

              {/* ── Right: Spline 3D Scene ── */}
              <div className="flex-1 relative min-h-[300px] md:min-h-0">
                {/* Fade mask on left edge so 3D blends into text side */}
                <div className="absolute left-0 inset-y-0 w-16 bg-gradient-to-r from-black/[0.96] to-transparent z-10 pointer-events-none" />
                <SplineScene
                  scene="https://prod.spline.design/kZDDjO5HuC9GJUM2/scene.splinecode"
                  className="w-full h-full"
                />
              </div>

            </div>
          </Card>
        </div>
      </section>

      {/* ── Integration Bar ── */}
      <section className="py-10 border-y border-white/5 bg-[#131936]/50">
        <div className="max-w-6xl mx-auto px-4">
          <p className="text-center text-white/30 text-xs uppercase tracking-widest mb-6">
            Powered by the best tools in the industry
          </p>
          <div className="flex flex-wrap justify-center gap-x-8 gap-y-3">
            {integrations.map((name) => (
              <span
                key={name}
                className="text-white/40 text-sm font-semibold hover:text-white/70 transition-colors cursor-default"
              >
                {name}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ── How It Works ── */}
      <section id="how-it-works" className="py-24 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <p className="text-[#00D4C8] text-xs font-bold uppercase tracking-widest mb-3">Simple Process</p>
            <h2 className="font-heading font-bold text-4xl md:text-5xl text-white">How it works</h2>
          </div>
          <div className="grid md:grid-cols-3 gap-8">
            {steps.map((step, i) => (
              <div key={i} className="relative">
                {i < steps.length - 1 && (
                  <div className="hidden md:block absolute top-8 left-full w-full h-px bg-gradient-to-r from-[#00D4C8]/30 to-transparent z-0" />
                )}
                <div className="bg-[#131936] border border-white/5 rounded-xl p-6 relative z-10 card-hover">
                  <div className="text-[#00D4C8] font-heading font-black text-4xl mb-4 opacity-60">{step.num}</div>
                  <h3 className="font-heading font-bold text-xl text-white mb-2">{step.title}</h3>
                  <p className="text-white/50 text-sm leading-relaxed">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ── */}
      <section id="features" className="py-24 px-4 bg-[#131936]/30">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <p className="text-[#00D4C8] text-xs font-bold uppercase tracking-widest mb-3">Everything You Need</p>
            <h2 className="font-heading font-bold text-4xl md:text-5xl text-white">Built for serious marketers</h2>
          </div>
          <div className="grid md:grid-cols-2 gap-6">
            {features.map(({ icon: Icon, title, desc }, i) => (
              <div key={i} className="bg-[#131936] border border-white/5 rounded-xl p-6 card-hover flex gap-4">
                <div className="w-10 h-10 rounded-lg bg-[#00D4C8]/10 flex items-center justify-center flex-shrink-0">
                  <Icon className="w-5 h-5 text-[#00D4C8]" strokeWidth={1.5} />
                </div>
                <div>
                  <h3 className="font-heading font-semibold text-lg text-white mb-1">{title}</h3>
                  <p className="text-white/50 text-sm leading-relaxed">{desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Pricing ── */}
      <section id="pricing" className="py-24 px-4">
        <div className="max-w-5xl mx-auto">
          <div className="text-center mb-16">
            <p className="text-[#00D4C8] text-xs font-bold uppercase tracking-widest mb-3">Transparent Pricing</p>
            <h2 className="font-heading font-bold text-4xl md:text-5xl text-white">Simple, predictable pricing</h2>
            <p className="text-white/50 mt-3 text-lg">No hidden fees. Cancel anytime.</p>
          </div>
          <div className="grid md:grid-cols-3 gap-6">
            {pricing.map(({ name, price, desc, features: f, highlight }) => (
              <div
                key={name}
                data-testid={`pricing-${name.toLowerCase()}`}
                className={`rounded-xl p-6 border relative ${
                  highlight ? "bg-[#00D4C8]/5 border-[#00D4C8]/30 teal-glow" : "bg-[#131936] border-white/5"
                }`}
              >
                {highlight && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2 bg-[#00D4C8] text-[#0A0F2E] text-xs font-bold px-3 py-1 rounded-full uppercase tracking-wide">
                    Most Popular
                  </div>
                )}
                <h3 className="font-heading font-bold text-xl text-white mb-1">{name}</h3>
                <p className="text-white/40 text-xs mb-4">{desc}</p>
                <div className="mb-6">
                  <span className="font-heading font-black text-4xl text-white">${price}</span>
                  <span className="text-white/40 text-sm">/mo</span>
                </div>
                <ul className="space-y-2 mb-6">
                  {f.map((item) => (
                    <li key={item} className="flex items-center gap-2 text-sm text-white/70">
                      <CheckCircle className="w-3.5 h-3.5 text-[#00D4C8] flex-shrink-0" />
                      {item}
                    </li>
                  ))}
                </ul>
                <button
                  onClick={handleCTA}
                  className={`w-full py-2.5 rounded-lg text-sm font-semibold transition-all ${highlight ? "btn-primary" : "btn-secondary"}`}
                >
                  Get Started
                </button>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA Banner ── */}
      <section className="py-20 px-4">
        <div className="max-w-3xl mx-auto">
          <Card className="bg-black/[0.96] border-white/[0.08] relative overflow-hidden hero-card-glow">
            <Spotlight className="-top-40 left-0 md:left-40 md:-top-20" fill="#00D4C8" />
            <div className="relative z-10 text-center p-12">
              <div className="flex justify-center gap-1 mb-4">
                {[...Array(5)].map((_, i) => <Star key={i} className="w-4 h-4 fill-[#00D4C8] text-[#00D4C8]" />)}
              </div>
              <h2 className="font-heading font-black text-4xl md:text-5xl mb-4 bg-clip-text text-transparent bg-gradient-to-b from-neutral-50 to-neutral-400">
                Ready to scale your<br />influencer marketing?
              </h2>
              <p className="text-neutral-400 mb-8 text-lg">
                Join brands running smarter campaigns with AI. Start for free today.
              </p>
              <button
                onClick={handleCTA}
                data-testid="bottom-cta-btn"
                className="btn-primary px-10 py-4 rounded-xl text-lg inline-flex items-center gap-2"
              >
                Start Your Campaign <ArrowRight className="w-5 h-5" />
              </button>
            </div>
          </Card>
        </div>
      </section>

      {/* ── Footer ── */}
      <footer className="border-t border-white/5 py-10 px-4">
        <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4 text-sm text-white/30">
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded bg-[#00D4C8] flex items-center justify-center">
              <Zap className="w-3 h-3 text-[#0A0F2E]" />
            </div>
            <span className="font-heading font-bold text-white/50">Influencer Connect</span>
          </div>
          <div className="flex gap-6">
            <a href="#" className="hover:text-white/60 transition-colors">Privacy</a>
            <a href="#" className="hover:text-white/60 transition-colors">Terms</a>
            <a href="#" className="hover:text-white/60 transition-colors">Contact</a>
          </div>
          <span>&copy; 2025 Influencer Connect. All rights reserved.</span>
        </div>
      </footer>

    </div>
  );
}
